apiVersion: v1
kind: Pod
metadata:
  name: k8scd-pod
  labels:
    app: k8scd
    
spec:
  containers:
    - name: k8scd
      image:  zigzigcheers/k8scd:main
      ports:
      - containerPort: 9876
      resources:
        limits:
          memory: 1024Mi
          cpu: '2'
        requests:
          memory: 64Mi
          cpu: '0.5'
      env:
        - name:  KV
          value: /kv
      volumeMounts:
        - mountPath: /kv
          name: k8scd-volume
  volumes:
  - name: k8scd-volume
    hostPath:
      path: "/var/local/k8scd-kv"
      type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name:  k8scd-service
spec:
  selector:
    app: k8scd
  type: LoadBalancer
  ports:
  - port: 9876
